kind: ConfigMap
apiVersion: v1
metadata:
  name: lightspeed-config
data:
  lightspeed-config.yaml: |
    proxy:
      endpoints:
        '/lightspeed/api':
          target: <url>
          headers:
            Authorization: Bearer <token>