kind: ConfigMap
apiVersion: v1
metadata:
  name: tekton-plugins
data:
  tekton-plugins.yaml: |
    plugins:
      # Installed plugins can be listed at:
      # https://DH_HOSTNAME/api/dynamic-plugins-info/loaded-plugins
      - disabled: false
        package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-tekton
        pluginConfig:
          dynamicPlugins:
            frontend:
              janus-idp.backstage-plugin-tekton:
                mountPoints:
                  - config:
                      if:
                        allOf:
                          - isTektonCIAvailable
                      layout:
                        gridColumn: 1 / -1
                        gridRowStart: 1
                    importName: TektonCI
                    mountPoint: entity.page.ci/cards
      - disabled: false
        package: ./dynamic-plugins/dist/backstage-plugin-kubernetes
      - disabled: false
        package: ./dynamic-plugins/dist/backstage-plugin-kubernetes-backend-dynamic
        pluginConfig:
          kubernetes:
            clusterLocatorMethods:
              - clusters:
                  - authProvider: serviceAccount
                    name: rhdh-kubernetes-plugin
                    serviceAccountToken: ${K8S_SA_TOKEN}
                    skipTLSVerify: true
                    url: https://kubernetes.default.svc
                type: config
            customResources:
              - apiVersion: v1
                group: route.openshift.io
                plural: routes
              - apiVersion: v1
                group: tekton.dev
                plural: pipelineruns
              - apiVersion: v1
                group: tekton.dev
                plural: taskruns
            serviceLocatorMethod:
              type: multiTenant
